version: "3.7"

services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.1
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    container_name: kibana
    image: kibana:7.6.1
    ports:
      - "0.0.0.0:5601:5601"

networks:
  default:
    external:
      name: elk

