filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"
  protocol: "http"
  ssl.enabled: false
